<template>
      <p class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-serif font-bold">Projects</p>
    <div  class="grid grid-cols-1 gap-2 sm:grid-cols-2 md:grid-cols-3 justify-center w-auto h-[75vh]">
    <div class="group flex flex-col justify-center items-center rounded-lg dark:bg-slate-900 bg-zinc-200 w-[20vw] my-[5vh] mx-[5vw] gap-[2vh] hover:border-2 border-sky-500"><img class="rounded w-[17vw]" src="../assets/shwhite.png"><div clas="flex justify-center items-center "><p class="group-hover:underline underline-offest-4 decoration-2 decoration-sky-500 text-xl font-semibold">Projects 1</p></div></div>
    <div class="group flex flex-col justify-center items-center rounded-lg dark:bg-slate-900 bg-zinc-200 w-[20vw] my-[5vh] mx-[5vw] gap-[2vh] hover:border-2 border-sky-500"><img class="rounded w-[17vw]" src="../assets/shdark.png"><div clas="flex justify-center items-center "><p class="group-hover:underline underline-offest-4 decoration-2 decoration-sky-500 text-xl font-semibold">Projects 2</p></div></div>
    <div class="group flex flex-col justify-center items-center rounded-lg dark:bg-slate-900 bg-zinc-200 w-[20vw] my-[5vh] mx-[5vw] gap-[2vh] hover:border-2 border-sky-500"><img class="rounded w-[17vw]" src="../assets/shwhite.png"><div clas="flex justify-center items-center "><p class="group-hover:underline underline-offest-4 decoration-2 decoration-sky-500 text-xl font-semibold">Projects 3</p></div></div>
    <div class="group flex flex-col justify-center items-center rounded-lg dark:bg-slate-900 bg-zinc-200 w-[20vw] my-[5vh] mx-[5vw] gap-[2vh] hover:border-2 border-sky-500"><img class="rounded w-[17vw]" src="../assets/shdark.png"><div clas="flex justify-center items-center "><p class="group-hover:underline underline-offest-4 decoration-2 decoration-sky-500 text-xl font-semibold">Projects 4</p></div></div>
    <div class="group flex flex-col justify-center items-center rounded-lg dark:bg-slate-900 bg-zinc-200 w-[20vw] my-[5vh] mx-[5vw] gap-[2vh] hover:border-2 border-sky-500"><img class="rounded w-[17vw]" src="../assets/shwhite.png"><div clas="flex justify-center items-center "><p class="group-hover:underline underline-offest-4 decoration-2 decoration-sky-500 text-xl font-semibold">Projects 5</p></div></div>
    <div class="group flex flex-col justify-center items-center rounded-lg dark:bg-slate-900 bg-zinc-200 w-[20vw] my-[5vh] mx-[5vw] gap-[2vh] hover:border-2 border-sky-500"><img class="rounded w-[17vw]" src="../assets/shdark.png"><div clas="flex justify-center items-center "><p class="group-hover:underline underline-offest-4 decoration-2 decoration-sky-500 text-xl font-semibold">Projects 6</p></div></div>
    </div>
</template>